-- Create invoices table so workers can track payments owed by customers.
-- invoice_number is auto-generated by a trigger (e.g. INV-0001).

CREATE SEQUENCE IF NOT EXISTS public.invoices_number_seq;

CREATE TABLE IF NOT EXISTS public.invoices (
  id            UUID         DEFAULT gen_random_uuid() NOT NULL,
  worker_id     UUID         NOT NULL REFERENCES public.workers(id),
  customer_id   UUID         NOT NULL REFERENCES public.users(id),
  booking_id    UUID         REFERENCES public.bookings(id),
  invoice_number TEXT        NOT NULL,
  service       TEXT,
  amount        NUMERIC(10, 2) NOT NULL,
  status        TEXT         NOT NULL DEFAULT 'Pending'
                CONSTRAINT invoices_status_check
                CHECK (status IN ('Paid', 'Pending', 'Overdue')),
  due_at        TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  DEFAULT now() NOT NULL,
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

-- Auto-generate invoice_number on INSERT
CREATE OR REPLACE FUNCTION public.set_invoice_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.invoice_number := 'INV-' || to_char(nextval('public.invoices_number_seq'::regclass), 'FM0000');
  RETURN NEW;
END;
$$;

CREATE TRIGGER before_invoice_insert
  BEFORE INSERT ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_invoice_number();

-- RLS
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Workers can read their own invoices"
  ON public.invoices FOR SELECT TO authenticated
  USING (
    worker_id IN (
      SELECT id FROM public.workers
      WHERE user_id = auth.uid() AND deleted_at IS NULL
    )
  );

CREATE POLICY "Customers can read their own invoices"
  ON public.invoices FOR SELECT TO authenticated
  USING (customer_id = auth.uid());

GRANT SELECT ON public.invoices TO authenticated;
