-- Intentionally empty.
-- A prior version of this migration attempted to backfill bookings.worker_id
-- to auth UUIDs, but the live FK is REFERENCES workers(id) so that direction
-- is wrong. worker_id must store workers.id. No data change needed.
